### ISSUE TITLE
iSmartgate

### ISSUE THREAD

**Issue by cemilbrowne** [vangorra/python_gogogate2_api#1]
This code does not appear to function correctly for the iSmartgate - which is a gogogate2 reskin, I believe.  

Specific error below, but I believe a POST is required based on homebridge-ismartgate:
`
b'<?xml version="1.0"?>\n\t\t\t\t<response>\n\t\t\t\t\t<error>\n\t\t\t\t\t\t<errorcode>21</errorcode>\n\t\t\t\t\t\t<errormsg>Error: token not set</errormsg>\t\n\t\t\t\t\t</error>\t\t\t\t\n\t\t\t\t</response>'
Traceback (most recent call last):
  File "test_gogogate.py", line 5, in <module>
    api.info()
  File "/usr/local/lib/python3.7/site-packages/gogogate2_api/__init__.py", line 104, in info
    return element_to_info_response(self._request("info"))
  File "/usr/local/lib/python3.7/site-packages/gogogate2_api/__init__.py", line 93, in _request
    response_text = self._api_cipher.decrypt(response.content)
  File "/usr/local/lib/python3.7/site-packages/gogogate2_api/__init__.py", line 44, in decrypt
    b64_decoded_bytes: Final[bytes] = base64.b64decode(enc[16:])
  File "/usr/local/Cellar/python/3.7.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
`

**Comment by cemilbrowne** [comment]
Looks like ismartgate needs a token to be passed in.

I sniffed the protocol to see if I could just pass in the same params as the official app, which I could, but I couldn't decode the response, which probably isn't a great sign....

**Comment by vangorra** [comment]
Sorry for the delay, I didn't see this issue.
Could you test this pull request? https://github.com/vangorra/python_gogogate2_api/pull/2 
I don't have an iSmartGate device.

**Comment by vangorra** [comment]
@cemilbrowne are you able to test the PR I posted above?

**Comment by cemilbrowne** [comment]
@vangorra - will do, can't do it this weekend.

**Comment by cemilbrowne** [comment]
wait; no got to it. Didn't work - sorry!

```
Traceback (most recent call last):
  File "./scripts/cli.py", line 103, in <module>
    cli()
  File "/Users/cemil/Documents/Coding/gogogate2/python_gogogate2_api/.venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/cemil/Documents/Coding/gogogate2/python_gogogate2_api/.venv/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/cemil/Documents/Coding/gogogate2/python_gogogate2_api/.venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/cemil/Documents/Coding/gogogate2/python_gogogate2_api/.venv/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/cemil/Documents/Coding/gogogate2/python_gogogate2_api/.venv/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/cemil/Documents/Coding/gogogate2/python_gogogate2_api/.venv/lib/python3.7/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./scripts/cli.py", line 81, in info
    PRETTY_PRINT.pprint(unpack(api.info()))
  File "/Users/cemil/Documents/Coding/gogogate2/python_gogogate2_api/gogogate2_api/__init__.py", line 147, in info
    return element_to_info_response(self._request("info"))
  File "/Users/cemil/Documents/Coding/gogogate2/python_gogogate2_api/gogogate2_api/__init__.py", line 136, in _request
    response_text = self._api_cipher.decrypt(response.content)
  File "/Users/cemil/Documents/Coding/gogogate2/python_gogogate2_api/gogogate2_api/__init__.py", line 46, in decrypt
    return ApiCipher.unpad(cipher.decrypt(b64_decoded_bytes))
  File "/Users/cemil/Documents/Coding/gogogate2/python_gogogate2_api/.venv/lib/python3.7/site-packages/Cryptodome/Cipher/_mode_cbc.py", line 246, in decrypt
    raise ValueError("Data must be padded to %d byte boundary in CBC mode" % self.block_size)
ValueError: Data must be padded to 16 byte boundary in CBC mode
```

**Comment by vangorra** [comment]
Actually this error is promising. You mentioned earlier you sniffed the protocol. Could you get me a sample of the request and response? I should be able to figure out out with that.
It would be good to create a temporary user or temporarily change your admin password before gathering the packets. Credentials are included in the request and response.

**Comment by vangorra** [comment]
Actually.. Don't post that here. The response also contains the URL for remote accessing your device, that's not something you want publicly posted. Can you email the request/response in a password protected zip and post the password to the zip file here? That will help reduce your risk.

**Comment by bdraco** [comment]
@vangorra If you send me your mailing details to nick@koston.org , when I get home next week, I'll ship you out the iSmartGate Lite I bought before I realized I needed the Pro version.  The firmware is the same on both of them.

**Comment by vangorra** [comment]
@bdraco I sent my information. Thanks for that. This is going to help a lot!

**Comment by cemilbrowne** [comment]
@vangorra - sorry it took me a while to get to this.  I am now unable to specify a cipher on latest branch; did a new checkout of ismartgate_support, git clone -b ismartgate_support https://github.com/vangorra/python_gogogate2_api.git, build, but cli doesn't have a cipher option - otherwise I'd be able to capture now.

**Comment by vangorra** [comment]
That's okay. @bdraco sent their spare device to me. I was able to capture the data and reverse engineer the protocol. I need to finish a couple tests but you can expect a version 2.0 soon.

**Comment by cemilbrowne** [comment]
@vangorra awesome; thanks - can't wait for that, and then we can integrate into Home Assistant. :)

**Comment by ghost** [comment]
I understand you are working on iSmartgate api but only the light version. I have the Pro and use two doors. The HomeKit Controller in Home Assistant do not detect the second door, however the Apple Home app does and also the iSmartGate app. I had GogoGate2 working on both doors but it got fried by lighting and was replaced by iSmartGate Pro.

I have tried to get your api that i found on Github and found that  both doors and sensors are detected. so now I'm eager to get it working on one Assistant as well! I am willing to test what ever code you have on my Pro version.

**Comment by bdraco** [comment]
This is going out in version 0.115 tomorrow
